management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://localhost:5432/test

  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

#otel:
#  metrics.exporter: prometheus
#  exporter:
#    prometheus:
#      port: 9464
#  service.name: spring-boot-app