name: Maven Test

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  
jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Surefire HTML Report
        run: |
          pwd
          ls -al
          mvn surefire-report:report

      - name: Disable Jekyll
        run: touch target/reports/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          name: surefire-report
          path: ./target/reports
          github_token: ${{ secrets.GITHUB_TOKEN }}
